Start of New Documentation
dogboy21/serializationisbad pull request #48
Opened 2023-07-31 22:21 UTC by Aiidoneus

This is the start of the new documentation while helping people understand what mods have been fixed by us and mod developers. By any means is it perfect but I think it does the job well.

2023-07-31 22:28 UTC, Aiidoneus commented
I know bdew is working on adding fixes for most versions of his mod. I will wait and add them all at once once 1.12 is fixed an pushed out to the public See #47

2023-07-31 22:56 UTC, Exaxxion reviewed
Assuming chart is accurate, that part LGTM. Please see review comments for suggestions re: the ReadMe.

2023-07-31 22:56 UTC, Exaxxion commented on README.md
> +Unlike the blog post stated above, there are plenty of mods that are and could be affected by this issue. Although some of them are already fixed in their latest versions, these mods were exploitable
I believe the last sentence of this paragraph should instead say "striving to keep" to maintain consistency with "trying to help" earlier in the sentence.

2023-07-31 22:56 UTC, Exaxxion commented on README.md
> +This list will change frequently as we find more mods that could have vulnerabilities and developers adding patches to their own mods. If you want to help us in keeping this list up-to-date, please f
"developers adding patches" -> "developers add patches" to keep consistent with "as we find".

Probably don't need "to it" after "contribute" as well but that's a stylistic choice.

2023-08-01 05:34 UTC, miozune commented
AsieLib and TecTech from https://github.com/dogboy21/serializationisbad/pull/33 are not listed

2023-08-01 07:49 UTC, Aiidoneus commented
> AsieLib and TecTech from #33 are not listed

I re-add those soon.

2023-08-01 09:16 UTC, Aiidoneus commented on README.md
> +Unlike the blog post stated above, there are plenty of mods that are and could be affected by this issue. Although some of them are already fixed in their latest versions, these mods were exploitable
Fixed via https://github.com/dogboy21/serializationisbad/pull/48/commits/fbaa9497d1e30fc83f632b7238b7678c56a56a20

2023-08-01 09:16 UTC, Aiidoneus commented on README.md
> +This list will change frequently as we find more mods that could have vulnerabilities and developers adding patches to their own mods. If you want to help us in keeping this list up-to-date, please f
Fixed via https://github.com/dogboy21/serializationisbad/pull/48/commits/fbaa9497d1e30fc83f632b7238b7678c56a56a20

2023-08-01 09:16 UTC, Aiidoneus commented
> AsieLib and TecTech from #33 are not listed

Fixed via https://github.com/dogboy21/serializationisbad/pull/48/commits/fbaa9497d1e30fc83f632b7238b7678c56a56a20

2023-08-01 10:30 UTC, miozune commented
`TechTech` -> `TecTech`
Also [AsieLib](https://github.com/dogboy21/serializationisbad/blob/master/serializationisbad.json#L152-L160) and [TecTech](https://github.com/dogboy21/serializationisbad/blob/master/serializationisbad.json#L97-L105) are already patched

2023-08-01 11:49 UTC, Aiidoneus commented
Thanks for the catch. This is what I get for doing this at 3 in the morning. 
Fixed via https://github.com/dogboy21/serializationisbad/pull/48/commits/c8eb2014ddbd0023ce0258fb3011462d8c5bb630

Updated README in various places

2023-08-01 16:54 UTC, dogboy21 requested changes

2023-08-01 16:54 UTC, dogboy21 commented on docs/mods.md
> +|                                                    [mxTune](https://www.curseforge.com/minecraft/mc-mods/mxtune)                                                     |
```suggestion
|                                                    [mxTune](https://www.curseforge.com/minecraft/mc-mods/mxtune)                                                     |                                                                                                             Only affects Minecraft versions<br>`1.12` to `1.16.5`                                                                                                             |                                                  Nothing is fixed in the affected versions                                                   |                ✅ <br> [Project Patch](https://github.com/dogboy21/serializationisbad/blob/master/serializationisbad.json#L263-L271)                 |                                                                                          |                                                                                                                    |
```

2023-08-01 17:35 UTC, dogboy21 approved these changes

2023-08-01 17:35 UTC, merged